# Generated by Django 2.1.5 on 2019-02-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Primary_Type', models.TextField(max_length=1000)),
                ('Description', models.TextField(max_length=1000)),
                ('Arrest', models.BooleanField()),
                ('Year', models.IntegerField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
            options={
                'db_table': 'crimes_table',
                'managed': True,
            },
        ),
    ]
