# Generated by Django 2.1.5 on 2019-02-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='Year',
        ),
    ]
